### PR TITLE
Process the `@Server` annotation

### LINKED ISSUE #522: Allowable values missing in generated OpenAPI (Swagger) YAML
### Steps to Reproduce

1. Micronaut + Java project
2. build.gradle
```
dependencies {
    annotationProcessor("io.micronaut.openapi:micronaut-openapi")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut:micronaut-runtime")
    implementation("io.swagger.core.v3:swagger-annotations:2.1.9")
    runtimeOnly("ch.qos.logback:logback-classic")
    implementation("io.micronaut:micronaut-validation")
}
```
3. application.java
```
@OpenAPIDefinition(
    info = @Info(
            title = "My Project",
            version = "1.0.0",
            description = "Let's rock",
            contact = @Contact(name = "Me", email = "me@company.com")
    ) ,
    extensions = {
            @Extension(name="x-api-id",
                    properties = @ExtensionProperty(name = "x-api-id", value="xxxx-xxxx-xxxx-xxxx-xxxxx")
            ),
            @Extension(name="x-audience",
                    properties = @ExtensionProperty(name="x-audience", value="component-internal")
            )
    },
    servers = {
            @Server(
                url="http://localhost:8080",
                variables = {
                        @ServerVariable(
                                allowableValues = {"v1", "v2"},
                                name = "service-version",
                                defaultValue = "v1"
                        )
                })
    }
)
public class Application {
    public static void main(String[] args) {
        Micronaut.run(Application.class, args);
    }
}
```

### Expected Behaviour

I expected that "allowableValues" are generated in my swagger yml file 

```
...
servers:
- url: http://localhost:8080
  variables:
    service-version:
      enum:
      - v1
      - v2
      default: v1
...
```

### Actual Behaviour
Generated swagger file is 

```
...
servers:
- url: http://localhost:8080
  variables:
    service-version:
      default: v1
...
```

The missing part is
      enum:
      - v1
      - v2

### Environment Information

- **Operating System**: Windows 10
- **Micronaut Version:** 2.5.3
- **JDK Version:** 16.0.1.9

### PR DESCRIPTION
**Pull request by ilopmar**
Fixes #522

This PR modifies some of the existing tests just to add missing tests, but it's not a breaking change.

### CODE REVIEW

File: openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiIncludeVisitorSpec.groovy [hunk 1]
```diff
@@ -29,24 +31,10 @@ import io.swagger.v3.oas.annotations.responses.ApiResponse;
                 license = @License(name = "Apache 2.0", url = "https://foo.bar"),
                 contact = @Contact(url = "https://gigantic-server.com", name = "Fred", email = "Fred@gigagantic-server.com")
         ),
-        tags = {
-                @Tag(name = "Tag 1", description = "desc 1", externalDocs = @ExternalDocumentation(description = "docs desc")),
-                @Tag(name = "Tag 2", description = "desc 2", externalDocs = @ExternalDocumentation(description = "docs desc 2")),
-                @Tag(name = "Tag 3")
-        },
```
Comment (ilopmar) [inline openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiIncludeVisitorSpec.groovy:36]: Removed because this test doesn't check anything related to `tags` (that is done in other tests)

File: openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiIncludeVisitorSpec.groovy [hunk 2]
```diff
@@ -29,24 +31,10 @@ import io.swagger.v3.oas.annotations.responses.ApiResponse;
...
                 @SecurityRequirement(name = "req 2", scopes = {"b", "c"})
-        },
-        servers = {
-                @Server(
-                        description = "server 1",
-                        url = "https://foo",
-                        variables = {
-                                @ServerVariable(name = "var1", description = "var 1", defaultValue = "1", allowableValues = {"1", "2"}),
-                                @ServerVariable(name = "var2", description = "var 2", defaultValue = "1", allowableValues = {"1", "2"})
-                        })
```
Comment (ilopmar) [inline openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiIncludeVisitorSpec.groovy:49]: Removed because this test doesn't check anything related to `servers` (that is done in other tests)
