### PR TITLE
Environments support

### LINKED ISSUE #166: Not resolving Micronaut config values in Controller annotation
Hi,

I have some config in my `@Controller` annotation, like this:

```
@Controller("/v${applications.api.version}/applications")
```

And my OpenAPI is being generated like this:

```
  /v${applications.api.version}/applications:
    get:
```

I believe that correct would be:

```
  /v1/applications:
    get:
```
Because I've stetted `${applications.api.version}` to 1:

Micronaut works fine, I'm able to resolve the controller `/v1/applications`.

Thanks a lot and great project!

### LINKED ISSUE #759: Micronaut OpenApi: Expand also placeholder not only in openapi.properties
### Feature description
**Current Behavior**
@OpenAPIDefinition only accepts constant values and placeholder from openapi.properties

**Expected Behavior**

- [ ]  Can we also expand the value for micronaut.server.context-path which in application.yml 
- [ ] Can we also expand or way to use the build-info.properties, build.version for OpenAPIDefinition

**Example**

_For Task 1_
```
@OpenAPIDefinition(
    info = @Info(servers = {@Server(url ="${micronaut.server.context-path}")	
    }
```

We intend to override the server url to context-path due to CORS issue upon invoking request with swagger-ui it was on HTTP while server host is at HTTPS

_For Task 2_
```
@OpenAPIDefinition(
    info = @Info(version  ="${build.version}")
 }
```

 Since the version in openapi definition is mostly same with the current version of the application service

### LINKED ISSUE #766: Placeholder expansion cannot be overridden by system properties.
### Expected Behavior

Based on these lines from the documentation:

> It is possible to tweak the OpenAPI processing with system properties or with a properties file. Options specified with system properties have priority over those defined in the openapi.properties file

> Properties prefixed with micronaut.openapi.expand will be expanded at compile time, for instance with:

it seems like it should be possible to supply `micronaut.openapi.expand.x` as a system property to inject values for placeholder expansion. 

### Actual Behaviour

Expandable placeholders are read from openapi.properties [here](https://github.com/micronaut-projects/micronaut-openapi/blob/29fb37e1d5b0d59401050e92ea70e397f6960dda/openapi/src/main/java/io/micronaut/openapi/visitor/OpenApiApplicationVisitor.java#L503), and therefore only values supplied in openapi.properties can be used to expand placeholders. 

Would it be possible to expand placeholders including overrides from system properties? Or failing that, at least update the documentation to reflect the fact that only values directly supplied from openapi.properties will be expanded?

Thank you!

### Steps To Reproduce

_No response_

### Environment Information

_No response_

### Example Application

_No response_

### Version

latest

### PR DESCRIPTION
**Pull request by altro3**
Finally added support standard properties application.yml with environments

Fixes #766 
Fixes #759 
Fixes #166

Merge it after https://github.com/micronaut-projects/micronaut-openapi/pull/791

### CODE REVIEW

**Comment by graemerocher** [comment]
@altro3 could you rebase? Thanks

**Comment by altro3** [comment]
@graemerocher yes, sure. But, please, don't merge this PR yet. I'm not sure that everything is working as intended at the moment. In Java, there are restrictions on the access of the annotation processor to the source code. Those. I'm not sure if this solution will work, I need to additionally test the library when it is included as an annotation processor. I'll try to test it over the weekend

**Comment by altro3** [comment]
Phew, I had to complicate the solution a bit due to java limitations, but I implemented the ability to use standard configurations for micronaut. I had to add the project keyword to identify the path to the yaml files that are in the project sources, because. when starting annotation processing, java does not provide access to the project files directly, that is, it does not load classes into the classpath and does not load resources.

Pull request can be merged

**Comment by altro3** [comment]
@graemerocher Phew, I had to complicate the solution a bit due to java limitations, but I implemented the ability to use standard configurations for micronaut. I had to add the project keyword to identify the path to the yaml files that are in the project sources, because. when starting annotation processing, java does not provide access to the project files directly, that is, it does not load classes into the classpath and does not load resources.

Pull request can be merged

File: openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java [hunk 1]
```diff
@@ -0,0 +1,180 @@
...
+    /**
+     * Construct a new environment for the given configuration.
+     *
+     * @param configuration The configuration
+     * @param context visitor context
+     */
+    public AnnProcessorEnvironment(ApplicationContextConfiguration configuration, VisitorContext context) {
+        super(configuration);
+
+        Path projectPath = context.getProjectDir().orElse(Paths.get(System.getProperty("user.dir")));
```
Comment (graemerocher) [inline openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java:67]: don't think we should be using the user directory like this. Better to just use `null` and do nothing

File: openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java [hunk 2]
```diff
@@ -0,0 +1,180 @@
...
+        projectDir = projectPath.toString().replaceAll("\\\\", "/");
```
Comment (graemerocher) [inline openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java:68]: this seems like a hack, why can't you just use `path.toUri()`?

**Review by graemerocher — CHANGES_REQUESTED** [review]

File: openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java (hunk 2 above)
Comment (altro3) [reply openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java]: fixed

File: openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java (hunk 1 above)
Comment (altro3) [reply openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java]: @graemerocher The problem is that when the tests are run, their directory is empty, because the processor is started for the generated classes. I agree that user.dir is only required for tests. Fixed

File: openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java (hunk 2 above)
Comment (altro3) [reply openapi/src/main/java/io/micronaut/openapi/visitor/AnnProcessorEnvironment.java]: @graemerocher Don't agree with you. This a stnadrad fix for windows. Why didn't I use `toUri` ? Let's see to example. My directory is `D:\Work\my-project` in windows and `/home/my/work/my-project`. I need to set this path as `file:D:\Work\my-project` for wind and `file:/home/my/work/my-project`.

If I use `path.toUri().toString()` than I have these paths: `file:///D:/Work/my-project/` for Windows and  `file:///D:/Work/my-project/` and `file:///home/my/work/my-project/`.

The problem is that in order to correctly display the correct path, I need to trim file and 3 slashes for Windows, and file and 2 slashes for Linux. In general, there are more problems than benefits from such a solution. My solution is simple and clear
