### PR TITLE
filter properties of type class

### LINKED ISSUE #10955: Warning 'Can't create array of wildcard' with stacktrace when compiling
### Expected Behavior

No warning is displayed

### Actual Behaviour

There is a warning `Can't create array of wildcard` with a big stacktrace when compiling a Micronaut application.

```
warning: Error with getting properties for class java.lang.Class: java.lang.UnsupportedOperationException: Can't create array of wildcard
  Can't create array of wildcard
> Task :webserver:compileJava
  java.lang.UnsupportedOperationException: Can't create array of wildcard
  	at io.micronaut.annotation.processing.visitor.JavaWildcardElement.withArrayDimensions(JavaWildcardElement.java:125)
  	at io.micronaut.inject.ast.ArrayableClassElement.toArray(ArrayableClassElement.java:27)
  	at io.micronaut.annotation.processing.visitor.AbstractJavaElement.newClassElement(AbstractJavaElement.java:282)
  	at io.micronaut.annotation.processing.visitor.AbstractJavaElement.newClassElement(AbstractJavaElement.java:213)
  	at io.micronaut.annotation.processing.visitor.AbstractJavaElement.newClassElement(AbstractJavaElement.java:191)
  	at io.micronaut.annotation.processing.visitor.JavaMethodElement.returnType(JavaMethodElement.java:340)
  	at io.micronaut.annotation.processing.visitor.JavaMethodElement.getGenericReturnType(JavaMethodElement.java:210)
  	at io.micronaut.inject.ast.utils.AstBeanPropertiesUtils.processGetter(AstBeanPropertiesUtils.java:244)
  	at io.micronaut.inject.ast.utils.AstBeanPropertiesUtils.resolveBeanProperties(AstBeanPropertiesUtils.java:105)
  	at io.micronaut.annotation.processing.visitor.JavaClassElement.getBeanProperties(JavaClassElement.java:343)
  	at io.micronaut.annotation.processing.visitor.JavaClassElement.getBeanProperties(JavaClassElement.java:298)
  	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.populateSchemaProperties(AbstractOpenApiVisitor.java:2455)
  	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.getSchemaDefinition(AbstractOpenApiVisitor.java:1966)
  	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.resolveSchema(AbstractOpenApiVisitor.java:983)
  	at io.micronaut.openapi.visitor.AbstractOpenApiVisitor.resolveSchema(AbstractOpenApiVisitor.java:927)
```

Complete stacktrace: 
[warning-micronaut-compile.txt](https://github.com/micronaut-projects/micronaut-core/files/14634954/warning-micronaut-compile.txt)

### Steps To Reproduce

_No response_

### Environment Information

_No response_

### Example Application

_No response_

### Version

4.3.4

### PR DESCRIPTION
**Pull request by graemerocher**
exclude all properties of type `java.lang.Class` and filter `Hidden/JsonIgnore` earlier in property query.

Note this does not fix https://github.com/micronaut-projects/micronaut-core/issues/10955 but does correct the behaviour of attempting to expose a type that can never be supported.

### CODE REVIEW

File: openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java [hunk 1]
```diff
@@ -2721,7 +2722,13 @@ private void populateSchemaProperties(OpenAPI openAPI, VisitorContext context, E
...
             try {
-                beanProperties = classElement.getBeanProperties().stream()
+                beanProperties = classElement.getBeanProperties(
+                        PropertyElementQuery.of(classElement)
+                            .excludedAnnotations(Set.of(
+                                Hidden.class.getName(),
+                                JsonIgnore.class.getName()
+                            ))
+                    ).stream()
                     .filter(p -> !"groovy.lang.MetaClass".equals(p.getType().getName()))
```
Comment (altro3) [inline openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java]: Need to change it to this:
```java
.filter(p -> !"groovy.lang.MetaClass".equals(p.getType().getName()) 
            && !"java.lang.Class".equals(p.getType().getName()))
```

**Review by altro3 — CHANGES_REQUESTED** [review]

**Comment by altro3** [comment]
You forgot to exclude  from bean properties with typ `java.lang.Class`. Now you exclude only fields, but sample with exception was with only getter method

**Review by altro3 — APPROVED** [review]
