### PR TITLE
Fix swagger-ui-bundle.js

### LINKED ISSUE #919: Swagger UI is blank
### Expected Behavior

The Swagger UI should be displayed when accessing its URL via browser (ending in `/swagger-ui`).

### Actual Behaviour

The Swagger UI is blank:

image

The Chrome debug console shows the following errors:

image

### Steps To Reproduce

I have followed the guidelines described here: https://micronaut-projects.github.io/micronaut-openapi/latest/guide/

Compiled the project using `./gradlew build` to produce the OpenAPI artifacts and then started the application with `./gradlew run`.

### Environment Information

- Operating System: Windows 11
- Java Runtime:
```
openjdk 17.0.5 2022-10-18
OpenJDK Runtime Environment GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08)
OpenJDK 64-Bit Server VM GraalVM CE 22.3.0 (build 17.0.5+8-jvmci-22.3-b08, mixed mode, sharing)
```

- `gradle.properties`:
```
micronautVersion=3.8.1
kotlinVersion=1.8.0
```

- `src/main/resources/application.yml`:
```yaml
micronaut:
  server:
    port: 5000
  data:
    pageable:
      max-page-size: 50
  metrics:
    enabled: true
    export:
      prometheus:
        enabled: true
        step: PT15S
        descriptions: true
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
```

- `build.gradle.kts`:
```kotlin
plugins {
    id("org.jetbrains.kotlin.jvm") version "1.8.0"
    id("org.jetbrains.kotlin.kapt") version "1.8.0"
    id("org.jetbrains.kotlin.plugin.allopen") version "1.8.0"
    id("groovy")
    id("com.github.johnrengelman.shadow") version "7.1.2"
    id("io.micronaut.application") version "3.7.0"
    id("io.micronaut.aot") version "3.7.0"
}

version = "0.1"
group = "com.strenux"

val kotlinVersion = project.properties["kotlinVersion"]

repositories {
    mavenCentral()
}

dependencies {
    compileOnly("org.graalvm.nativeimage:svm")

    //    implementation("io.micronaut.security:micronaut-security-annotations")
    implementation("io.micronaut.data:micronaut-data-jdbc")
    implementation("io.micronaut.email:micronaut-email-javamail")
    implementation("io.micronaut.email:micronaut-email-template")
    implementation("io.micronaut.flyway:micronaut-flyway")
    implementation("io.micronaut.kotlin:micronaut-kotlin-runtime")
    implementation("io.micronaut.micrometer:micronaut-micrometer-registry-prometheus")
    implementation("io.micronaut.problem:micronaut-problem-json")
    implementation("io.micronaut.reactor:micronaut-reactor")
    implementation("io.micronaut.reactor:micronaut-reactor-http-client")
    implementation("io.micronaut.security:micronaut-security-jwt")
    implementation("io.micronaut.security:micronaut-security-oauth2")
    implementation("io.micronaut.serde:micronaut-serde-jackson")
    implementation("io.micronaut.sql:micronaut-jdbc-hikari")
    implementation("io.micronaut.tracing:micronaut-tracing-jaeger")
    implementation("io.micronaut.views:micronaut-views-thymeleaf")
    implementation("io.micronaut:micronaut-http-client")
    implementation("io.micronaut:micronaut-management")
    implementation("io.micronaut:micronaut-validation")
    implementation("io.temporal:temporal-sdk:1.17.0")
    implementation("jakarta.annotation:jakarta.annotation-api")
    implementation("jakarta.persistence:jakarta.persistence-api:2.2.3")
    implementation("org.apache.commons:commons-lang3:3.12.0")
    implementation("org.http4k:http4k-client-apache:4.37.0.0")
    implementation("org.jetbrains.kotlin:kotlin-reflect:${kotlinVersion}")
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8:${kotlinVersion}")
    implementation("org.slf4j:slf4j-api:2.0.6")
    implementation("org.springframework.security:spring-security-crypto:6.0.1")
    implementation("io.swagger.core.v3:swagger-annotations")


    kapt("io.micronaut.data:micronaut-data-processor")
    kapt("io.micronaut.serde:micronaut-serde-processor")
    kapt("io.micronaut:micronaut-http-validation")
    kapt("io.micronaut.openapi:micronaut-openapi:4.8.2")

    runtimeOnly("ch.qos.logback:logback-classic:1.4.5")
    runtimeOnly("com.fasterxml.jackson.module:jackson-module-kotlin")
    runtimeOnly("commons-logging:commons-logging:1.2")
    runtimeOnly("org.postgresql:postgresql")
}

application {
    mainClass.set("com.strenux.app.Application")
}

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

tasks {
    compileKotlin {
        kotlinOptions {
            jvmTarget = "17"
        }
    }
    compileTestKotlin {
        kotlinOptions {
            jvmTarget = "17"
        }
    }
}

graalvmNative.toolchainDetection.set(false)

micronaut {
    runtime("netty")
    testRuntime("spock2")
    processing {
        incremental(true)
        annotations("com.strenux.*")
    }
    aot {
        // Please review carefully the optimizations enabled below
        // Check https://micronaut-projects.github.io/micronaut-aot/latest/guide/ for more details
        optimizeServiceLoading.set(true)
        convertYamlToJava.set(true)
        precomputeOperations.set(true)
        cacheEnvironment.set(true)
        optimizeClassLoading.set(true)
        deduceEnvironment.set(true)
        optimizeNetty.set(true)
    }
    kapt {
        arguments {
            arg(
                "micronaut.openapi.views.spec",
                "-Dmicronaut.openapi.views.spec=rapidoc.enabled=true,swagger-ui.enabled=true"
            )
        }
    }
}

allOpen {
    annotations("io.micronaut.http.annotation.Controller")
}
```

### Example Application

_No response_

### Version

3.8.1

### PR DESCRIPTION
**Pull request by altro3**
Fixed #919

### CODE REVIEW

**Comment by altro3** [comment]
@graemerocher Hi! Could you merge PRs #920, #923, #919 and finilize release 4.8.3? This bug is critical for swagger UI.

Also could you close these isssues:

https://github.com/micronaut-projects/micronaut-openapi/issues/900
https://github.com/micronaut-projects/micronaut-openapi/issues/903
https://github.com/micronaut-projects/micronaut-openapi/issues/907
https://github.com/micronaut-projects/micronaut-openapi/issues/911
https://github.com/micronaut-projects/micronaut-openapi/issues/912
https://github.com/micronaut-projects/micronaut-openapi/issues/551 (fixed early)

They all fixed in 4.8.2.

And close these issues too:

https://github.com/micronaut-projects/micronaut-openapi/issues/924
https://github.com/micronaut-projects/micronaut-openapi/issues/921
https://github.com/micronaut-projects/micronaut-openapi/issues/919

**Comment by sdelamo** [comment]
> Currently away until next week. Maybe @sdelamo can help

Yes, I will check it out before 3.8.4

File: openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java [hunk 1]
```diff
@@ -788,9 +788,8 @@ protected Schema resolveSchema(OpenAPI openAPI, @Nullable Element definingElemen
                     .findFirst()
                     .flatMap(ClassElement::getFirstTypeArgument)
                     .orElse(null);
-            }
```
Comment (sdelamo) [inline openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java:791]: is this change related to https://github.com/micronaut-projects/micronaut-openapi/issues/919 ?

**Review by sdelamo — APPROVED** [review]

**Review by sdelamo — APPROVED** [review]
