### PR TITLE
Fix generating models with polymorphism

### LINKED ISSUE #1794: OpenAPI Polimorfizm issue in controller
### Expected Behavior

I have OpenApi model with inheritance and polimorfizm like:

BaseInvoiceDto:

````java
    BaseInvoiceDto:
      type: object
      required:
        - sellerVatId
        - docType
      properties:
        docType:
          $ref: '#/components/schemas/DocType'
        sellerVatId:
          type: string
          maxLength: 10
...
      discriminator:
        propertyName: docType
        mapping:
          FS: "#/components/schemas/SalesInvoiceCreateDto"
          FW: "#/components/schemas/CurrencyInvoiceCreateDto"
````
and two child classes:

````
    SalesInvoiceCreateDto:
      allOf:
        - $ref: '#/components/schemas/BaseInvoiceDto'
    CurrencyInvoiceCreateDto:
      allOf:
        - $ref: '#/components/schemas/SalesInvoiceCreateDto'
        - type: object
          properties:
            currency:
              type: string
              description: "Currency of the invoice"
              default: "PLN"
            exchangeRate:
              type: number
              description: "Exchange rate for the currency"
            exchangeDate:
              type: string
              format: date
          required:
            - currency
            - exchangeRate
            - exchangeDate
````

almost all works fine, expect controller part. Generator create interface `CreateInvoiceRequest` and makes it parameter of controller method:

```yaml
  /api/invoice:
    post:
      tags:
        - Invoice
      operationId: createInvoice
      summary: Creates new sale invoice
      requestBody:
        required: true
        content:
          application/json:
            schema:
              oneOf:
                - $ref: '#/components/schemas/SalesInvoiceCreateDto'
                - $ref: '#/components/schemas/CurrencyInvoiceCreateDto'
```

````java
    @Operation(
        operationId = "createInvoice",
        summary = "Creates new sale invoice",
        responses = {
            @ApiResponse(responseCode = "201", description = "Invoice created correctly", content = @Content(mediaType = "application/json", schema = @Schema(implementation = InvoiceIdDto.class))),
            @ApiResponse(responseCode = "403", description = "No access to cost center with Manager rights", content = @Content(mediaType = "application/json", schema = @Schema(implementation = ErrorDTO.class)))
        },
        security = @SecurityRequirement(name = "bearerAuth")
    )
    @Post("/api/invoice")
    @Secured(SecurityRule.IS_AUTHENTICATED)
    HttpResponse<@Valid InvoiceIdDto> createInvoice(
        @Body @NotNull @Valid CreateInvoiceRequest createInvoiceRequest
    );
````

```
public class SalesInvoiceCreateDto extends BaseInvoiceDto implements CreateInvoiceRequest 
```
and
```
public class CurrencyInvoiceCreateDto extends SalesInvoiceCreateDto implements CreateInvoiceRequest
```

when I call this controller I got error:

````
Failed to convert argument [invoice] for value [null] due to: Unable to deserialize type [interface dev.itrust.fk.api.model.CreateInvoiceRequest]: No default constructor exists"
````

but if I manually change parameter type to `BaseInvoiceDto` all works fine. What is propose of creating `CreateInvoiceRequest` interface and why it is controller parametr?

### Actual Behaviour

controller not works

### Steps To Reproduce

_No response_

### Environment Information

- Linux Mint
- JDK 21

### Example Application

_No response_

### Version

4.6.1, 4.6.2

### PR DESCRIPTION
**Pull request by altro3**
Fixed #1794

### CODE REVIEW

File: openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java [hunk 1]
```diff
@@ -1726,12 +1731,13 @@ private void processOneOfModels(CodegenModel model, Collection<ModelsMap> models
...
     }
 
-    private void processProperty(CodegenProperty property, boolean isServer, Map<String, ModelsMap> models) {
+    private void processProperty(CodegenProperty property, boolean isServer, CodegenModel model, Map<String, ModelsMap> models) {
 
         property.vendorExtensions.put("inRequiredArgsConstructor", !property.isReadOnly || isServer);
         property.vendorExtensions.put("isServer", isServer);
         property.vendorExtensions.put("lombok", lombok);
         property.vendorExtensions.put("defaultValueIsNotNull", property.defaultValue != null && !property.defaultValue.equals("null"));
+        property.vendorExtensions.put("x-implements", model.vendorExtensions.get("x-implements"));
```
Comment (sdelamo) [inline openapi-generator/src/main/java/io/micronaut/openapi/generator/AbstractMicronautJavaCodegen.java:1740]: is this extension `x-implements` documented anywhere?

**Review by sdelamo — APPROVED** [review]
