### PR TITLE
Fix generation of multi-dimensional arrays

### LINKED ISSUE #367: Incorrect OpenAPI is generated for multi-dimensional arrays
According to https://swagger.io/docs/specification/data-models/data-types/#array:

> [...] Arrays can be nested:
> ```yaml
>    # [ [1, 2], [3, 4] ]
>    type: array
>    items:
>      type: array
>      items:
>        type: integer
> ```
... but `micronaut-openapi` doesn't seem to support that feature yet.

### Steps to Reproduce

1. Declare a @Schema on a nested array type, for instance:
```java
@Schema
class MyClass
{
  @ArraySchema(arraySchema = @Schema(description = "int[][]"))
  public int[][] nestedInts;

  @ArraySchema(arraySchema = @Schema(description = "List<List<Integer>>"))
  public List<List<Integer>> nestedIntegers;
}
```

### Expected Behaviour

Nested arrays:
```yaml
components:
  schemas:
    MyClass:
      type: object
      properties:
        nestedInts:
          type: array
          description: "int[][]"
          items:
            type: array
            items:
              type: integer
              format: int32
        nestedIntegers:
          type: array
          description: List<List<Integer>>
          items:
            type: array
            items:
              type: integer
              format: int32
```

### Actual Behaviour

A "Flat" array for native integers (wrong depth), and an array of objects of type `List_Integer_` for the nested `List<Integer>`s:
```yaml
components:
  schemas:
    MyClass:
      type: object
      properties:
        nestedInts:
          type: array
          description: "int[][]"
          items:
            type: integer
            format: int32
        nestedIntegers:
          type: array
          description: List<List<Integer>>
          items:
            $ref: '#/components/schemas/List_Integer_'
    List_Integer_:
      type: object
      properties:
        empty:
          type: boolean
```

### Environment Information

(not relevant to the problem)
- **Operating System**: Ubuntu 20.04.1 LTS 
- **Micronaut Version:** 2.1.2
- **JDK Version:** openjdk version "1.8.0_272"

### Dependencies

- micronaut-projects/micronaut-core#2573 (Already an array exception in annotation processor)
- micronaut-projects/micronaut-core#3850 (Add support for multi dimensional arrays in introspections)

### PR DESCRIPTION
**Pull request by rdesgroppes**
Fixes #367

### CODE REVIEW

File: gradle.properties [hunk 1]
```diff
@@ -2,7 +2,7 @@ projectVersion=2.1.1.BUILD-SNAPSHOT
 micronautBuildVersion=1.1.5
 jacksonVersion=2.11.2
 micronautDocsVersion=1.0.24
-micronautVersion=2.0.1
+micronautVersion=2.1.2
```
Comment (ilopmar) [inline gradle.properties:5]: Unless this is really necessary (which I don't think it is), it's better to keep this module in Micronaut 2.0. This way users that don't want to upgrade can still use it (because everything happens at compile time).

Comment (rdesgroppes) [reply gradle.properties]: Thanks, @ilopmar. Accordingly, I narrowed down the version bump to the bare minimum.

File: openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiArraySchemaSpec.groovy [hunk 2]
```diff
@@ -50,6 +50,12 @@ class Pets {
 
     @ArraySchema(arraySchema = @Schema(description = "a list of primitive Ids", nullable = false), minItems = 2, schema = @Schema(description = "Yes", nullable = true))
     public long[] primitiveIds;
+
+    @ArraySchema(arraySchema = @Schema(description = "a nested list of Pets"))
+    public List<List<Pet>> nestedPets;
+
+    @ArraySchema(arraySchema = @Schema(description = "a nested list of primitive Ids"))
+    public long[][][] nestedPrimitiveIds;
```
Comment (rdesgroppes) [inline openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiArraySchemaSpec.groovy:58]: Missing test (and impl) for non-primitive arrays.

**Comment by graemerocher** [comment]
Could you fix the checkstyle issues?

**Comment by rdesgroppes** [comment]
> Could you fix the checkstyle issues?

Am on it. Sorry for the inconvenience!

File: openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiArraySchemaSpec.groovy (hunk 2 above)
Comment (rdesgroppes) [reply openapi/src/test/groovy/io/micronaut/openapi/visitor/OpenApiArraySchemaSpec.groovy]: Done.

File: openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java [hunk 3]
```diff
@@ -666,18 +667,25 @@ private Map toTupleSubMap(Object[] a, String entryKey, String entryValue) {
                         }
                     }
                 } else if (type.isIterable()) {
-                    if (primitiveType == null) {
+                    if (type.getArrayDimensions() > 1 || type.isArray() && type.isAssignable(Iterable.class)) {
```
Comment (rdesgroppes) [inline openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java:670]: could be simplified

Comment (rdesgroppes) [reply openapi/src/main/java/io/micronaut/openapi/visitor/AbstractOpenApiVisitor.java]: Done.

**Comment by graemerocher** [comment]
Thanks for the contribution!

**Comment by rdesgroppes** [comment]
You're welcome, @graemerocher!
