### PR TITLE
Fix generating default values

### LINKED ISSUE #1686: Default Values not working unless type is a String with enum values
### Expected Behavior

> [!NOTE]
> OpenApi's Kotlin generator just has default values in the comments, so micronaut's tool is already doing more
> `* @param contentType  (optional, default to "application/json")`

Have both the annotation mention a `defaultValue` correctly AND the paramater set to it. The `defaultValue` only being in the Annotation still requires you to define it when using the client and that is tedious for my use case. 

In general, I'd probably be better off generating some lower-level client than micronaut's Declarative client for 1 complex API we have and if that's the recommendation that's fine too. I need to modify the headers, path params, etc dynamically but most of the time the default is fine.

Given this spec

```yaml
paths:
  '/{apiVersion}/orders':
    get:
      summary: 'Browser/search multiple order'
      operationId: browseSearchOrders
      parameters:
        - $ref: '#/components/parameters/XFavorToken'
        - $ref: '#/components/parameters/XToken'
        - $ref: '#/components/parameters/ApiVersion'
components:
  parameters:
    ApiVersion:
      name: apiVersion
      in: path
      description: 'Api Version as a path parameter'
      required: true
      schema:
        type: string
        default: v5
    ContentType:
      name: Content-Type
      in: header
      required: false
      schema:
        type: string
        default: application/json
        nullable: true
    XFavorToken:
      name: X-Favor-Token
      in: header
      description: 'Legacy token header for v5 and older APIs'
      required: false
      schema:
        type: string
        default: null
        nullable: true
```

```kotlin
@Header(name = "X-Favor-User-Agent") @Nullable xFavorUserAgent: String? = null,
@PathVariable(name = "apiVersion", defaultValue = "v5") @Nullable apiVersion: ApiVersionParam? = "v5",
@Header(name = "Content-Type", defaultValue = "application/json") @Nullable contentType: String? = "application/json"
```

### Actual Behaviour

1. Defaults of null are ignored
2. Defaults that do not contain enum have double set of quotes around defaultValue
3. params are never set to default value, just the annotation.

```kotlin
@Header(name = "X-Favor-User-Agent") @Nullable xFavorUserAgent: String?,
@PathVariable(name = "apiVersion", defaultValue = ""v5"") @Nullable apiVersion: String?,
@Header(name = "Content-Type", defaultValue = ""application/json"") @Nullable contentType: String? 
```

Oddly if I make the apiVersion one a enum list of value and default to v5 it works

```yaml
components:
  parameters:
    ApiVersion:
      name: apiVersion
      in: path
      description: 'Api Version as a path parameter'
      required: false
      schema:
        type: string
        default: v5
        enum:
          - v1
          - v2
          - v3
          - v4
          - v5
          - v6
          - v7
```

```kotlin
@Header(name = "X-Favor-User-Agent") @Nullable xFavorUserAgent: String?,
@PathVariable(name = "apiVersion", defaultValue = "v5") @Nullable apiVersion: ApiVersionParam?,
@Header(name = "Content-Type", defaultValue = ""application/json"") @Nullable contentType: String? 
```

### Steps To Reproduce

```yaml
components:
  parameters:
    ApiVersion:
      name: apiVersion
      in: path
      description: 'Api Version as a path parameter'
      required: true
      schema:
        type: string
        default: v5
    ContentType:
      name: Content-Type
      in: header
      required: false
      schema:
        type: string
        default: application/json
        nullable: true
    XFavorToken:
      name: X-Favor-Token
      in: header
      description: 'Legacy token header for v5 and older APIs'
      required: false
      schema:
        type: string
        default: null
        nullable: true
```

### Environment Information

_No response_

### Example Application

_No response_

### Version

4.5.1

### PR DESCRIPTION
**Pull request by altro3**
Fixed #1686

### CODE REVIEW

File: openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java [hunk 1]
```diff
@@ -550,4 +550,17 @@ void testOneOfWithoutDiscriminator() {
...
+    void testParamsWithDefaultValue() {
+
+        var codegen = new KotlinMicronautClientCodegen();
+        String outputPath = generateFiles(codegen, "src/test/resources/3_0/params-with-default-value.yml", CodegenConstants.APIS, CodegenConstants.MODELS);
+        String path = outputPath + "src/main/kotlin/org/openapitools/";
+
+        assertFileContains(path + "api/DefaultApi.kt",
+            "@PathVariable(name = \"apiVersion\", defaultValue = \"v5\") @Nullable apiVersion: BrowseSearchOrdersApiVersionParameter? = BrowseSearchOrdersApiVersionParameter.V5,",
+            "@Header(name = \"Content-Type\", defaultValue = \"application/json\") @Nullable contentType: String? = \"application/json\""
+        );
```
Comment (scprek) [inline openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java:600]: The last case I was hoping for is `XFavorToken` default null to work. Is that easy to add?

```kotlin
@Header("X-Favor-Token") @Nullable xFavorToken: String? = null
```

Not sure you'd even have a defaultValue in the annotation for null since it has to be a string

**Review by scprek — CHANGES_REQUESTED** [review]

**Comment by scprek** [comment]
Looking good, I got the same! Question about the default: null ones tho.


```kotlin
        @PathVariable(name = "apiVersion", defaultValue = "v5") @NotNull apiVersion: ApiVersion = ApiVersion.V5,
        @Header("X-Favor-Token") @Nullable xFavorToken: String?,
        @Header(name = "Content-Type", defaultValue = "application/json") @Nullable contentType: String? = "application/json"
```

File: openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java (hunk 1 above)
Comment (altro3) [reply openapi-generator/src/test/java/io/micronaut/openapi/generator/KotlinMicronautClientCodegenTest.java:600]: fixed

**Review by scprek — APPROVED** [review]
Amazing Thanks! Default null worked in my test.

**Comment by scprek** [comment]
Will this get into 6.12 snapshot soon?

**Comment by sdelamo** [comment]
@altro3 can you merge 6.12.x into this branch?

**Comment by altro3** [comment]
@sdelamo done

**Comment by sdelamo** [comment]
@altro3 can you merge 6.12.x into this branch?

**Comment by scprek** [comment]
Noticed 1 possible issue, but can open a new ticket https://github.com/micronaut-projects/micronaut-openapi/issues/1686#issuecomment-2304781186
